# Generated by Django 4.2.4 on 2023-10-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartWay_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
