# Generated by Django 4.2.4 on 2023-10-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartWay_app', '0002_student_joining_date_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='FeeSubmitDate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.IntegerField(null=True),
        ),
    ]
