# Generated by Django 4.2.4 on 2023-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartWay_app', '0003_student_feesubmitdate_student_clas'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Fee',
            field=models.IntegerField(null=True),
        ),
    ]
